name: main branch auto ci process script

on: # 아래 job을 실행시킬 action
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_PEM_KEY }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        script: 
            cd /var/lib/jenkins/jenkins-deploy/chance_doe_repository
            git pull
