name: deploy code test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      uses: mobaXterm/ssh-action@v23.2
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_PEM_KEY }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        script:
          cd /var/lib/jenkins/jenkins-deploy/chance_doe_repository
          git pull
